export const LOCALES = [
  "en",
  "ar",
  "de",
  "es",
  "fr",
  "he",
  "hi",
  "id",
  "it",
  "ja",
  "ko",
  "nl",
  "pl",
  "pt",
  "ro",
  "ru",
  "th",
  "tr",
  "uk",
  "vi",
  "zh",
  "zh-tw",
  "bn",
  "cs",
  "ha",
  "sv",
  "tl",
  "yo"
] as const;

export type LocaleKey = (typeof LOCALES)[number];

export interface UiStrings {
  home: string;
  breadcrumb: string;
  about: string;
  messageTypes: string;
  selectionGuide: string;
  api: string;
  contact: string;
  privacy: string;
  terms: string;
  author: string;
  editorial: string;
  structuredAddress: string;
  faq: string;
  glossary: string;
  pacsExplained: string;
  changelog: string;
  langMenuLabel: string;
  skipToContentLabel: string;
  returnToTopLabel: string;
  outlineLabel: string;
  appearanceLabel: string;
  lightModeSwitchTitle: string;
  darkModeSwitchTitle: string;
  searchButtonText: string;
  searchButtonAriaLabel: string;
  lastUpdatedText: string;
  footerMessage: string;
  footerCopyright: string;
  footerNavLabel: string;
  documentation: string;
  resources: string;
  legal: string;
  releases: string;
  opensInNewTab: string;
  mainNavigation: string;
  extraNavigation: string;
  mobileNavigation: string;
  toggleDarkMode: string;
  github: string;
  pypi: string;
  docs: string;
  copyright: string;
  navMessages: string;
  navResources: string;
}

const en: UiStrings = {
  home: "Home",
  breadcrumb: "Breadcrumb",
  about: "What is pacs.008?",
  messageTypes: "Message Types",
  selectionGuide: "Handbook",
  api: "API",
  contact: "Contact",
  privacy: "Privacy",
  terms: "Terms",
  author: "Author",
  editorial: "Editorial policy",
  structuredAddress: "Structured address deadline",
  faq: "FAQ",
  glossary: "Glossary",
  pacsExplained: "Technical details",
  changelog: "Changelog",
  langMenuLabel: "Change language",
  skipToContentLabel: "Skip to content",
  returnToTopLabel: "Return to top",
  outlineLabel: "On this page",
  appearanceLabel: "Appearance",
  lightModeSwitchTitle: "Switch to light theme",
  darkModeSwitchTitle: "Switch to dark theme",
  searchButtonText: "Search",
  searchButtonAriaLabel: "Search",
  lastUpdatedText: "Last updated",
  footerMessage: "Open-source ISO 20022 tooling for financial teams and engineers.",
  footerCopyright: "Copyright © Sebastien Rousseau 2026",
  footerNavLabel: "Footer navigation",
  documentation: "Documentation",
  resources: "Resources",
  legal: "Legal",
  releases: "Releases",
  opensInNewTab: "(opens in new tab)",
  mainNavigation: "Main Navigation",
  extraNavigation: "extra navigation",
  mobileNavigation: "mobile navigation",
  toggleDarkMode: "Toggle dark mode",
  github: "GitHub",
  pypi: "PyPI",
  docs: "About pacs.008",
  copyright: "Copyright",
  navMessages: "Messages",
  navResources: "Resources"
};

export const UI_STRINGS: Record<LocaleKey, Partial<UiStrings>> = {
  en,
  ar: { home: "الرئيسية", breadcrumb: "مسار التنقل", about: "ما هو pacs.008؟", messageTypes: "أنواع الرسائل", selectionGuide: "الدليل", api: "واجهة البرمجة", contact: "اتصل", privacy: "الخصوصية", terms: "الشروط", editorial: "السياسة التحريرية", structuredAddress: "موعد العنوان المنظم", langMenuLabel: "تغيير اللغة", skipToContentLabel: "تخطي إلى المحتوى", returnToTopLabel: "العودة إلى الأعلى", outlineLabel: "في هذه الصفحة", appearanceLabel: "المظهر", lightModeSwitchTitle: "التبديل إلى السمة الفاتحة", darkModeSwitchTitle: "التبديل إلى السمة الداكنة", searchButtonText: "بحث", searchButtonAriaLabel: "بحث", lastUpdatedText: "آخر تحديث", footerMessage: "أدوات ISO 20022 مفتوحة المصدر للفرق المالية والمهندسين.", footerCopyright: "حقوق النشر © Sebastien Rousseau 2026", footerNavLabel: "تنقل التذييل", documentation: "الوثائق", resources: "الموارد", legal: "قانوني", releases: "الإصدارات", opensInNewTab: "(يفتح في علامة تبويب جديدة)", mainNavigation: "التنقل الرئيسي", extraNavigation: "تنقل إضافي", mobileNavigation: "تنقل الهاتف", toggleDarkMode: "تبديل الوضع الداكن", github: "GitHub", pypi: "PyPI", docs: "حول pacs.008", pacsExplained: "التفاصيل الفنية", copyright: "حقوق النشر", navMessages: "الرسائل", navResources: "الموارد" },
  de: { home: "Start", breadcrumb: "Breadcrumb-Navigation", about: "Was ist pacs.008?", messageTypes: "Nachrichtentypen", selectionGuide: "Handbuch", api: "API", contact: "Kontakt", privacy: "Datenschutz", terms: "Bedingungen", editorial: "Redaktionelle Richtlinie", structuredAddress: "Frist für strukturierte Adressen", langMenuLabel: "Sprache ändern", skipToContentLabel: "Zum Inhalt springen", returnToTopLabel: "Nach oben", outlineLabel: "Auf dieser Seite", appearanceLabel: "Darstellung", lightModeSwitchTitle: "Zum hellen Design wechseln", darkModeSwitchTitle: "Zum dunklen Design wechseln", searchButtonText: "Suchen", searchButtonAriaLabel: "Suchen", lastUpdatedText: "Zuletzt aktualisiert", footerMessage: "Open-Source-ISO-20022-Werkzeuge für Finanzteams und Ingenieure.", footerCopyright: "Urheberrecht © Sebastien Rousseau 2026", footerNavLabel: "Fußzeilennavigation", documentation: "Dokumentation", resources: "Ressourcen", legal: "Rechtliches", releases: "Veröffentlichungen", opensInNewTab: "(öffnet in neuem Tab)", mainNavigation: "Hauptnavigation", extraNavigation: "zusätzliche Navigation", mobileNavigation: "mobile Navigation", toggleDarkMode: "Dunkelmodus umschalten", github: "GitHub", pypi: "PyPI", docs: "Über pacs.008", pacsExplained: "Technische Details", copyright: "Urheberrecht" , navMessages: "Nachrichten", navResources: "Ressourcen" },
  es: { home: "Inicio", breadcrumb: "Ruta de navegación", about: "¿Qué es pacs.008?", messageTypes: "Tipos de mensaje", selectionGuide: "Manual", api: "API", contact: "Contacto", privacy: "Privacidad", terms: "Términos", editorial: "Política editorial", structuredAddress: "Plazo de dirección estructurada", langMenuLabel: "Cambiar idioma", skipToContentLabel: "Saltar al contenido", returnToTopLabel: "Volver arriba", outlineLabel: "En esta página", appearanceLabel: "Apariencia", lightModeSwitchTitle: "Cambiar al tema claro", darkModeSwitchTitle: "Cambiar al tema oscuro", searchButtonText: "Buscar", searchButtonAriaLabel: "Buscar", lastUpdatedText: "Última actualización", footerMessage: "Herramientas ISO 20022 de código abierto para equipos financieros e ingenieros.", footerCopyright: "Copyright © Sebastien Rousseau 2026", footerNavLabel: "Navegación del pie", documentation: "Documentación", resources: "Recursos", legal: "Aviso legal", releases: "Versiones", opensInNewTab: "(se abre en una pestaña nueva)", mainNavigation: "Navegación principal", extraNavigation: "navegación adicional", mobileNavigation: "navegación móvil", toggleDarkMode: "Alternar modo oscuro", github: "GitHub", pypi: "PyPI", docs: "Sobre pacs.008", pacsExplained: "Detalles técnicos", copyright: "Derechos" , navMessages: "Mensajes", navResources: "Recursos" },
  fr: { home: "Accueil", breadcrumb: "Fil d’Ariane", about: "Qu'est-ce que pacs.008 ?", messageTypes: "Types de messages", selectionGuide: "Manuel", api: "API", contact: "Contact", privacy: "Confidentialité", terms: "Conditions", editorial: "Politique éditoriale", structuredAddress: "Échéance adresse structurée", langMenuLabel: "Changer de langue", skipToContentLabel: "Aller au contenu", returnToTopLabel: "Retour en haut", outlineLabel: "Sur cette page", appearanceLabel: "Apparence", lightModeSwitchTitle: "Passer au thème clair", darkModeSwitchTitle: "Passer au thème sombre", searchButtonText: "Rechercher", searchButtonAriaLabel: "Rechercher", lastUpdatedText: "Dernière mise à jour", footerMessage: "Outils ISO 20022 open source pour les équipes financières et les ingénieurs.", footerCopyright: "Copyright © Sebastien Rousseau 2026", footerNavLabel: "Navigation du pied de page", documentation: "Documentation", resources: "Ressources", legal: "Mentions légales", releases: "Versions", opensInNewTab: "(s’ouvre dans un nouvel onglet)", mainNavigation: "Navigation principale", extraNavigation: "navigation supplémentaire", mobileNavigation: "navigation mobile", toggleDarkMode: "Basculer le mode sombre", github: "GitHub", pypi: "PyPI", docs: "À propos de pacs.008", pacsExplained: "Détails techniques", copyright: "Droits d'auteur" , navMessages: "Messages", navResources: "Ressources" },
  he: { home: "בית", breadcrumb: "נתיב ניווט", about: "?מהו pacs.008", messageTypes: "סוגי הודעות", selectionGuide: "מדריך", api: "API", contact: "יצירת קשר", privacy: "פרטיות", terms: "תנאים", editorial: "מדיניות עריכה", structuredAddress: "מועד כתובת מובנית", langMenuLabel: "שינוי שפה", skipToContentLabel: "דלג לתוכן", returnToTopLabel: "חזרה למעלה", outlineLabel: "בעמוד זה", appearanceLabel: "מראה", lightModeSwitchTitle: "מעבר לערכת נושא בהירה", darkModeSwitchTitle: "מעבר לערכת נושא כהה", searchButtonText: "חיפוש", searchButtonAriaLabel: "חיפוש", lastUpdatedText: "עודכן לאחרונה", footerMessage: "כלי ISO 20022 בקוד פתוח לצוותים פיננסיים ומהנדסים.", footerCopyright: "זכויות יוצרים © Sebastien Rousseau 2026", footerNavLabel: "ניווט תחתון", documentation: "תיעוד", resources: "משאבים", legal: "משפטי", releases: "גרסאות", opensInNewTab: "(נפתח בלשונית חדשה)", mainNavigation: "ניווט ראשי", extraNavigation: "ניווט נוסף", mobileNavigation: "ניווט לנייד", toggleDarkMode: "החלפת מצב כהה", github: "GitHub", pypi: "PyPI", docs: "אודות pacs.008", pacsExplained: "פרטים טכניים", copyright: "זכויות יוצרים" , navMessages: "הודעות", navResources: "משאבים" },
  hi: { home: "होम", breadcrumb: "ब्रेडक्रम्ब", about: "pacs.008 क्या है?", messageTypes: "संदेश प्रकार", selectionGuide: "हैंडबुक", api: "API", contact: "संपर्क", privacy: "गोपनीयता", terms: "शर्तें", editorial: "संपादकीय नीति", structuredAddress: "संरचित पता समय सीमा", langMenuLabel: "भाषा बदलें", skipToContentLabel: "सामग्री पर जाएँ", returnToTopLabel: "ऊपर लौटें", outlineLabel: "इस पेज पर", appearanceLabel: "रूप", lightModeSwitchTitle: "हल्की थीम पर जाएँ", darkModeSwitchTitle: "गहरी थीम पर जाएँ", searchButtonText: "खोजें", searchButtonAriaLabel: "खोजें", lastUpdatedText: "अंतिम अपडेट", footerMessage: "वित्तीय टीमों और इंजीनियरों के लिए ओपन-सोर्स ISO 20022 टूलिंग।", footerCopyright: "कॉपीराइट © Sebastien Rousseau 2026", footerNavLabel: "फ़ुटर नेविगेशन", documentation: "प्रलेखन", resources: "संसाधन", legal: "कानूनी", releases: "रिलीज़", opensInNewTab: "(नए टैब में खुलता है)", mainNavigation: "मुख्य नेविगेशन", extraNavigation: "अतिरिक्त नेविगेशन", mobileNavigation: "मोबाइल नेविगेशन", toggleDarkMode: "डार्क मोड बदलें", github: "GitHub", pypi: "PyPI", docs: "pacs.008 के बारे में", pacsExplained: "तकनीकी विवरण", copyright: "कॉपीराइट" , navMessages: "संदेश", navResources: "संसाधन" },
  id: { home: "Beranda", about: "Apa itu pacs.008?", messageTypes: "Jenis pesan", selectionGuide: "Buku panduan", api: "API", contact: "Kontak", privacy: "Privasi", terms: "Ketentuan", editorial: "Kebijakan editorial", structuredAddress: "Tenggat alamat terstruktur", langMenuLabel: "Ganti bahasa", skipToContentLabel: "Lewati ke konten", returnToTopLabel: "Kembali ke atas", outlineLabel: "Di halaman ini", appearanceLabel: "Tampilan", lightModeSwitchTitle: "Beralih ke tema terang", darkModeSwitchTitle: "Beralih ke tema gelap", searchButtonText: "Cari", searchButtonAriaLabel: "Cari", lastUpdatedText: "Terakhir diperbarui", footerMessage: "Perkakas ISO 20022 sumber terbuka untuk tim keuangan dan insinyur.", footerCopyright: "Hak cipta © Sebastien Rousseau 2026", footerNavLabel: "Navigasi footer", documentation: "Dokumentasi", resources: "Sumber daya", legal: "Hukum", releases: "Rilis", opensInNewTab: "(terbuka di tab baru)", mainNavigation: "Navigasi utama", extraNavigation: "navigasi tambahan", mobileNavigation: "navigasi seluler", toggleDarkMode: "Alihkan mode gelap", github: "GitHub", pypi: "PyPI", docs: "Tentang pacs.008", pacsExplained: "Detail teknis", copyright: "Hak cipta" , navMessages: "Pesan", navResources: "Sumber Daya" },
  it: { home: "Home", about: "Cos'è pacs.008?", messageTypes: "Tipi di messaggio", selectionGuide: "Manuale", api: "API", contact: "Contatti", privacy: "Privacy", terms: "Termini", editorial: "Politica editoriale", structuredAddress: "Scadenza indirizzo strutturato", langMenuLabel: "Cambia lingua", skipToContentLabel: "Vai al contenuto", returnToTopLabel: "Torna in alto", outlineLabel: "In questa pagina", appearanceLabel: "Aspetto", lightModeSwitchTitle: "Passa al tema chiaro", darkModeSwitchTitle: "Passa al tema scuro", searchButtonText: "Cerca", searchButtonAriaLabel: "Cerca", lastUpdatedText: "Ultimo aggiornamento", footerMessage: "Strumenti ISO 20022 open source per team finanziari e ingegneri.", footerCopyright: "Copyright © Sebastien Rousseau 2026", footerNavLabel: "Navigazione del piè di pagina", documentation: "Documentazione", resources: "Risorse", legal: "Legale", releases: "Versioni", opensInNewTab: "(si apre in una nuova scheda)", mainNavigation: "Navigazione principale", extraNavigation: "navigazione aggiuntiva", mobileNavigation: "navigazione mobile", toggleDarkMode: "Attiva/disattiva modalità scura", github: "GitHub", pypi: "PyPI", docs: "Informazioni su pacs.008", pacsExplained: "Dettagli tecnici", copyright: "Copyright" , navMessages: "Messaggi", navResources: "Risorse" },
  ja: { home: "ホーム", about: "pacs.008 とは？", messageTypes: "メッセージ種別", selectionGuide: "ハンドブック", api: "API", contact: "お問い合わせ", privacy: "プライバシー", terms: "利用規約", editorial: "編集ポリシー", structuredAddress: "構造化住所の期限", langMenuLabel: "言語を変更", skipToContentLabel: "コンテンツへ移動", returnToTopLabel: "上に戻る", outlineLabel: "このページ", appearanceLabel: "表示", lightModeSwitchTitle: "ライトテーマに切り替え", darkModeSwitchTitle: "ダークテーマに切り替え", searchButtonText: "検索", searchButtonAriaLabel: "検索", lastUpdatedText: "最終更新", footerMessage: "金融チームとエンジニア向けのオープンソース ISO 20022 ツール。", footerCopyright: "著作権 © Sebastien Rousseau 2026", footerNavLabel: "フッターナビゲーション", documentation: "ドキュメント", resources: "リソース", legal: "法的情報", releases: "リリース", opensInNewTab: "（新しいタブで開きます）", mainNavigation: "メインナビゲーション", extraNavigation: "追加ナビゲーション", mobileNavigation: "モバイルナビゲーション", toggleDarkMode: "ダークモードを切り替え", github: "GitHub", pypi: "PyPI", docs: "pacs.008 について", pacsExplained: "技術詳細", copyright: "著作権" , navMessages: "メッセージ", navResources: "リソース" },
  ko: { home: "홈", about: "pacs.008란?", messageTypes: "메시지 유형", selectionGuide: "핸드북", api: "API", contact: "문의", privacy: "개인정보", terms: "약관", editorial: "편집 정책", structuredAddress: "구조화 주소 기한", langMenuLabel: "언어 변경", skipToContentLabel: "본문으로 건너뛰기", returnToTopLabel: "맨 위로", outlineLabel: "이 페이지", appearanceLabel: "표시", lightModeSwitchTitle: "라이트 테마로 전환", darkModeSwitchTitle: "다크 테마로 전환", searchButtonText: "검색", searchButtonAriaLabel: "검색", lastUpdatedText: "마지막 업데이트", footerMessage: "금융 팀과 엔지니어를 위한 오픈소스 ISO 20022 도구.", footerCopyright: "저작권 © Sebastien Rousseau 2026", footerNavLabel: "바닥글 탐색", documentation: "문서", resources: "리소스", legal: "법적 고지", releases: "릴리스", opensInNewTab: "(새 탭에서 열림)", mainNavigation: "기본 탐색", extraNavigation: "추가 탐색", mobileNavigation: "모바일 탐색", toggleDarkMode: "다크 모드 전환", github: "GitHub", pypi: "PyPI", docs: "pacs.008 소개", pacsExplained: "기술 세부사항", copyright: "저작권" , navMessages: "메시지", navResources: "리소스" },
  nl: { home: "Home", about: "Wat is pacs.008?", messageTypes: "Berichttypen", selectionGuide: "Handboek", api: "API", contact: "Contact", privacy: "Privacy", terms: "Voorwaarden", editorial: "Redactioneel beleid", structuredAddress: "Deadline gestructureerd adres", langMenuLabel: "Taal wijzigen", skipToContentLabel: "Ga naar inhoud", returnToTopLabel: "Terug naar boven", outlineLabel: "Op deze pagina", appearanceLabel: "Weergave", lightModeSwitchTitle: "Schakel naar licht thema", darkModeSwitchTitle: "Schakel naar donker thema", searchButtonText: "Zoeken", searchButtonAriaLabel: "Zoeken", lastUpdatedText: "Laatst bijgewerkt", footerMessage: "Open-source ISO 20022-hulpmiddelen voor financiële teams en engineers.", footerCopyright: "Auteursrecht © Sebastien Rousseau 2026", footerNavLabel: "Voettekstnavigatie", documentation: "Documentatie", resources: "Bronnen", legal: "Juridisch", releases: "Releases", opensInNewTab: "(opent in nieuw tabblad)", mainNavigation: "Hoofdnavigatie", extraNavigation: "extra navigatie", mobileNavigation: "mobiele navigatie", toggleDarkMode: "Donkere modus wisselen", github: "GitHub", pypi: "PyPI", docs: "Over pacs.008", pacsExplained: "Technische details", copyright: "Auteursrecht" , navMessages: "Berichten", navResources: "Bronnen" },
  pl: { home: "Strona główna", about: "Czym jest pacs.008?", messageTypes: "Typy wiadomości", selectionGuide: "Podręcznik", api: "API", contact: "Kontakt", privacy: "Prywatność", terms: "Warunki", editorial: "Polityka redakcyjna", structuredAddress: "Termin adresu strukturalnego", langMenuLabel: "Zmień język", skipToContentLabel: "Przejdź do treści", returnToTopLabel: "Wróć do góry", outlineLabel: "Na tej stronie", appearanceLabel: "Wygląd", lightModeSwitchTitle: "Przełącz na jasny motyw", darkModeSwitchTitle: "Przełącz na ciemny motyw", searchButtonText: "Szukaj", searchButtonAriaLabel: "Szukaj", lastUpdatedText: "Ostatnia aktualizacja", footerMessage: "Otwarte narzędzia ISO 20022 dla zespołów finansowych i inżynierów.", footerCopyright: "Prawa autorskie © Sebastien Rousseau 2026", footerNavLabel: "Nawigacja stopki", documentation: "Dokumentacja", resources: "Zasoby", legal: "Informacje prawne", releases: "Wydania", opensInNewTab: "(otwiera się w nowej karcie)", mainNavigation: "Nawigacja główna", extraNavigation: "dodatkowa nawigacja", mobileNavigation: "nawigacja mobilna", toggleDarkMode: "Przełącz tryb ciemny", github: "GitHub", pypi: "PyPI", docs: "O pacs.008", pacsExplained: "Szczegóły techniczne", copyright: "Prawa autorskie" , navMessages: "Komunikaty", navResources: "Zasoby" },
  pt: { home: "Início", about: "O que é o pacs.008?", messageTypes: "Tipos de mensagem", selectionGuide: "Manual", api: "API", contact: "Contato", privacy: "Privacidade", terms: "Termos", editorial: "Política editorial", structuredAddress: "Prazo de endereço estruturado", langMenuLabel: "Mudar idioma", skipToContentLabel: "Ir para o conteúdo", returnToTopLabel: "Voltar ao topo", outlineLabel: "Nesta página", appearanceLabel: "Aparência", lightModeSwitchTitle: "Mudar para o tema claro", darkModeSwitchTitle: "Mudar para o tema escuro", searchButtonText: "Pesquisar", searchButtonAriaLabel: "Pesquisar", lastUpdatedText: "Última atualização", footerMessage: "Ferramentas ISO 20022 de código aberto para equipes financeiras e engenheiros.", footerCopyright: "Copyright © Sebastien Rousseau 2026", footerNavLabel: "Navegação do rodapé", documentation: "Documentação", resources: "Recursos", legal: "Informações legais", releases: "Lançamentos", opensInNewTab: "(abre em uma nova guia)", mainNavigation: "Navegação principal", extraNavigation: "navegação extra", mobileNavigation: "navegação móvel", toggleDarkMode: "Alternar modo escuro", github: "GitHub", pypi: "PyPI", docs: "Sobre o pacs.008", pacsExplained: "Detalhes técnicos", copyright: "Direitos autorais" , navMessages: "Mensagens", navResources: "Recursos" },
  ro: { home: "Acasă", about: "Ce este pacs.008?", messageTypes: "Tipuri de mesaje", selectionGuide: "Manual", api: "API", contact: "Contact", privacy: "Confidențialitate", terms: "Termeni", editorial: "Politică editorială", structuredAddress: "Termen adresă structurată", langMenuLabel: "Schimbă limba", skipToContentLabel: "Mergi la conținut", returnToTopLabel: "Înapoi sus", outlineLabel: "Pe această pagină", appearanceLabel: "Aspect", lightModeSwitchTitle: "Comută la tema luminoasă", darkModeSwitchTitle: "Comută la tema întunecată", searchButtonText: "Caută", searchButtonAriaLabel: "Caută", lastUpdatedText: "Ultima actualizare", footerMessage: "Instrumente ISO 20022 open-source pentru echipe financiare și ingineri.", footerCopyright: "Drepturi de autor © Sebastien Rousseau 2026", footerNavLabel: "Navigare în subsol", documentation: "Documentație", resources: "Resurse", legal: "Aspecte legale", releases: "Lansări", opensInNewTab: "(se deschide într-o filă nouă)", mainNavigation: "Navigare principală", extraNavigation: "navigare suplimentară", mobileNavigation: "navigare mobilă", toggleDarkMode: "Comută modul întunecat", github: "GitHub", pypi: "PyPI", docs: "Despre pacs.008", pacsExplained: "Detalii tehnice", copyright: "Drepturi de autor" , navMessages: "Mesaje", navResources: "Resurse" },
  ru: { home: "Главная", about: "Что такое pacs.008?", messageTypes: "Типы сообщений", selectionGuide: "Справочник", api: "API", contact: "Контакты", privacy: "Конфиденциальность", terms: "Условия", editorial: "Редакционная политика", structuredAddress: "Срок структурированного адреса", langMenuLabel: "Сменить язык", skipToContentLabel: "Перейти к содержимому", returnToTopLabel: "Наверх", outlineLabel: "На этой странице", appearanceLabel: "Оформление", lightModeSwitchTitle: "Переключить на светлую тему", darkModeSwitchTitle: "Переключить на тёмную тему", searchButtonText: "Поиск", searchButtonAriaLabel: "Поиск", lastUpdatedText: "Последнее обновление", footerMessage: "Инструменты ISO 20022 с открытым исходным кодом для финансовых команд и инженеров.", footerCopyright: "Авторские права © Sebastien Rousseau 2026", footerNavLabel: "Навигация в подвале", documentation: "Документация", resources: "Ресурсы", legal: "Правовая информация", releases: "Релизы", opensInNewTab: "(открывается в новой вкладке)", mainNavigation: "Основная навигация", extraNavigation: "дополнительная навигация", mobileNavigation: "мобильная навигация", toggleDarkMode: "Переключить тёмный режим", github: "GitHub", pypi: "PyPI", docs: "О pacs.008", pacsExplained: "Технические подробности", copyright: "Авторские права" , navMessages: "Сообщения", navResources: "Ресурсы" },
  th: { home: "หน้าแรก", about: "pacs.008 คืออะไร?", messageTypes: "ประเภทข้อความ", selectionGuide: "คู่มือ", api: "API", contact: "ติดต่อ", privacy: "ความเป็นส่วนตัว", terms: "ข้อกำหนด", editorial: "นโยบายบรรณาธิการ", structuredAddress: "กำหนดเวลาที่อยู่แบบมีโครงสร้าง", langMenuLabel: "เปลี่ยนภาษา", skipToContentLabel: "ข้ามไปยังเนื้อหา", returnToTopLabel: "กลับไปด้านบน", outlineLabel: "ในหน้านี้", appearanceLabel: "การแสดงผล", lightModeSwitchTitle: "สลับเป็นธีมสว่าง", darkModeSwitchTitle: "สลับเป็นธีมมืด", searchButtonText: "ค้นหา", searchButtonAriaLabel: "ค้นหา", lastUpdatedText: "อัปเดตล่าสุด", footerMessage: "เครื่องมือ ISO 20022 แบบโอเพนซอร์สสำหรับทีมการเงินและวิศวกร", footerCopyright: "ลิขสิทธิ์ © Sebastien Rousseau 2026", footerNavLabel: "การนำทางส่วนท้าย", documentation: "เอกสาร", resources: "ทรัพยากร", legal: "กฎหมาย", releases: "รีลีส", opensInNewTab: "(เปิดในแท็บใหม่)", mainNavigation: "การนำทางหลัก", extraNavigation: "การนำทางเพิ่มเติม", mobileNavigation: "การนำทางบนมือถือ", toggleDarkMode: "สลับโหมดมืด", github: "GitHub", pypi: "PyPI", docs: "เกี่ยวกับ pacs.008", pacsExplained: "รายละเอียดทางเทคนิค", copyright: "ลิขสิทธิ์" , navMessages: "ข้อความ", navResources: "ทรัพยากร" },
  tr: { home: "Ana sayfa", about: "pacs.008 nedir?", messageTypes: "Mesaj türleri", selectionGuide: "El kitabı", api: "API", contact: "İletişim", privacy: "Gizlilik", terms: "Koşullar", editorial: "Yayın politikası", structuredAddress: "Yapılandırılmış adres son tarihi", langMenuLabel: "Dili değiştir", skipToContentLabel: "İçeriğe geç", returnToTopLabel: "Yukarı dön", outlineLabel: "Bu sayfada", appearanceLabel: "Görünüm", lightModeSwitchTitle: "Açık temaya geç", darkModeSwitchTitle: "Koyu temaya geç", searchButtonText: "Ara", searchButtonAriaLabel: "Ara", lastUpdatedText: "Son güncelleme", footerMessage: "Finans ekipleri ve mühendisler için açık kaynaklı ISO 20022 araçları.", footerCopyright: "Telif hakkı © Sebastien Rousseau 2026", footerNavLabel: "Alt bilgi gezintisi", documentation: "Dokümantasyon", resources: "Kaynaklar", legal: "Yasal", releases: "Sürümler", opensInNewTab: "(yeni sekmede açılır)", mainNavigation: "Ana gezinme", extraNavigation: "ek gezinme", mobileNavigation: "mobil gezinme", toggleDarkMode: "Karanlık modu değiştir", github: "GitHub", pypi: "PyPI", docs: "pacs.008 Hakkında", pacsExplained: "Teknik detaylar", copyright: "Telif hakkı" , navMessages: "Mesajlar", navResources: "Kaynaklar" },
  uk: { home: "Головна", about: "Що таке pacs.008?", messageTypes: "Типи повідомлень", selectionGuide: "Довідник", api: "API", contact: "Контакти", privacy: "Конфіденційність", terms: "Умови", editorial: "Редакційна політика", structuredAddress: "Термін структурованої адреси", langMenuLabel: "Змінити мову", skipToContentLabel: "Перейти до вмісту", returnToTopLabel: "Повернутися вгору", outlineLabel: "На цій сторінці", appearanceLabel: "Вигляд", lightModeSwitchTitle: "Перемкнути на світлу тему", darkModeSwitchTitle: "Перемкнути на темну тему", searchButtonText: "Пошук", searchButtonAriaLabel: "Пошук", lastUpdatedText: "Останнє оновлення", footerMessage: "Відкриті інструменти ISO 20022 для фінансових команд та інженерів.", footerCopyright: "Авторське право © Sebastien Rousseau 2026", footerNavLabel: "Навігація в нижньому колонтитулі", documentation: "Документація", resources: "Ресурси", legal: "Правова інформація", releases: "Релізи", opensInNewTab: "(відкривається в новій вкладці)", mainNavigation: "Основна навігація", extraNavigation: "додаткова навігація", mobileNavigation: "мобільна навігація", toggleDarkMode: "Перемкнути темний режим", github: "GitHub", pypi: "PyPI", docs: "Про pacs.008", pacsExplained: "Технічні деталі", copyright: "Авторське право" , navMessages: "Повідомлення", navResources: "Ресурси" },
  vi: { home: "Trang chủ", about: "pacs.008 là gì?", messageTypes: "Loại thông điệp", selectionGuide: "Sổ tay", api: "API", contact: "Liên hệ", privacy: "Quyền riêng tư", terms: "Điều khoản", editorial: "Chính sách biên tập", structuredAddress: "Hạn chót địa chỉ có cấu trúc", langMenuLabel: "Đổi ngôn ngữ", skipToContentLabel: "Chuyển đến nội dung", returnToTopLabel: "Quay lại đầu trang", outlineLabel: "Trên trang này", appearanceLabel: "Giao diện", lightModeSwitchTitle: "Chuyển sang giao diện sáng", darkModeSwitchTitle: "Chuyển sang giao diện tối", searchButtonText: "Tìm kiếm", searchButtonAriaLabel: "Tìm kiếm", lastUpdatedText: "Cập nhật lần cuối", footerMessage: "Công cụ ISO 20022 mã nguồn mở cho đội ngũ tài chính và kỹ sư.", footerCopyright: "Bản quyền © Sebastien Rousseau 2026", footerNavLabel: "Điều hướng chân trang", documentation: "Tài liệu", resources: "Tài nguyên", legal: "Pháp lý", releases: "Bản phát hành", opensInNewTab: "(mở trong tab mới)", mainNavigation: "Điều hướng chính", extraNavigation: "điều hướng bổ sung", mobileNavigation: "điều hướng di động", toggleDarkMode: "Chuyển chế độ tối", github: "GitHub", pypi: "PyPI", docs: "Về pacs.008", pacsExplained: "Chi tiết kỹ thuật", copyright: "Bản quyền" , navMessages: "Thông điệp", navResources: "Tài nguyên" },
  zh: { home: "首页", about: "什么是 pacs.008？", messageTypes: "报文类型", selectionGuide: "手册", api: "API", contact: "联系", privacy: "隐私", terms: "条款", editorial: "编辑政策", structuredAddress: "结构化地址截止日期", langMenuLabel: "切换语言", skipToContentLabel: "跳到内容", returnToTopLabel: "返回顶部", outlineLabel: "本页内容", appearanceLabel: "外观", lightModeSwitchTitle: "切换到浅色主题", darkModeSwitchTitle: "切换到深色主题", searchButtonText: "搜索", searchButtonAriaLabel: "搜索", lastUpdatedText: "最后更新", footerMessage: "面向金融团队和工程师的开源 ISO 20022 工具。", footerCopyright: "版权 © Sebastien Rousseau 2026", footerNavLabel: "页脚导航", documentation: "文档", resources: "资源", legal: "法律", releases: "发布", opensInNewTab: "（在新标签页打开）", mainNavigation: "主导航", extraNavigation: "附加导航", mobileNavigation: "移动导航", toggleDarkMode: "切换深色模式", github: "GitHub", pypi: "PyPI", docs: "关于 pacs.008", pacsExplained: "技术详情", copyright: "版权" , navMessages: "消息", navResources: "资源" },
  "zh-tw": { home: "首頁", about: "什麼是 pacs.008？", messageTypes: "訊息類型", selectionGuide: "手冊", api: "API", contact: "聯絡", privacy: "隱私", terms: "條款", editorial: "編輯政策", structuredAddress: "結構化地址截止日期", langMenuLabel: "切換語言", skipToContentLabel: "跳至內容", returnToTopLabel: "返回頂部", outlineLabel: "本頁內容", appearanceLabel: "外觀", lightModeSwitchTitle: "切換至淺色主題", darkModeSwitchTitle: "切換至深色主題", searchButtonText: "搜尋", searchButtonAriaLabel: "搜尋", lastUpdatedText: "最後更新", footerMessage: "面向金融團隊與工程師的開源 ISO 20022 工具。", footerCopyright: "版權 © Sebastien Rousseau 2026", footerNavLabel: "頁尾導覽", documentation: "文件", resources: "資源", legal: "法律", releases: "發行版本", opensInNewTab: "（在新分頁開啟）", mainNavigation: "主導覽", extraNavigation: "額外導覽", mobileNavigation: "行動導覽", toggleDarkMode: "切換深色模式", github: "GitHub", pypi: "PyPI", docs: "關於 pacs.008", pacsExplained: "技術詳情", copyright: "版權" , navMessages: "訊息", navResources: "資源" },
  bn: { home: "হোম", breadcrumb: "ব্রেডক্রাম্ব", about: "pacs.008 কী?", messageTypes: "বার্তার ধরন", selectionGuide: "হ্যান্ডবুক", api: "API", contact: "যোগাযোগ", privacy: "গোপনীয়তা", terms: "শর্তাবলী", editorial: "সম্পাদকীয় নীতি", structuredAddress: "কাঠামোবদ্ধ ঠিকানার সময়সীমা", faq: "প্রশ্নোত্তর", glossary: "শব্দকোষ", changelog: "পরিবর্তন তালিকা", langMenuLabel: "ভাষা পরিবর্তন", skipToContentLabel: "বিষয়বস্তুতে যান", returnToTopLabel: "শীর্ষে ফিরুন", outlineLabel: "এই পৃষ্ঠায়", appearanceLabel: "চেহারা", lightModeSwitchTitle: "হালকা থিমে যান", darkModeSwitchTitle: "গাঢ় থিমে যান", searchButtonText: "অনুসন্ধান", searchButtonAriaLabel: "অনুসন্ধান", lastUpdatedText: "সর্বশেষ আপডেট", footerMessage: "আর্থিক দল ও প্রকৌশলীদের জন্য ওপেন-সোর্স ISO 20022 টুলিং।", footerCopyright: "কপিরাইট © Sebastien Rousseau 2026", footerNavLabel: "ফুটার নেভিগেশন", documentation: "ডকুমেন্টেশন", resources: "রিসোর্স", legal: "আইনি", releases: "রিলিজ", opensInNewTab: "(নতুন ট্যাবে খুলবে)", mainNavigation: "প্রধান নেভিগেশন", extraNavigation: "অতিরিক্ত নেভিগেশন", mobileNavigation: "মোবাইল নেভিগেশন", toggleDarkMode: "ডার্ক মোড টগল", github: "GitHub", pypi: "PyPI", docs: "pacs.008 সম্পর্কে", pacsExplained: "প্রযুক্তিগত বিবরণ", copyright: "কপিরাইট", navMessages: "বার্তা", navResources: "রিসোর্স" },
  cs: { home: "Domů", breadcrumb: "Drobečková navigace", about: "Co je pacs.008?", messageTypes: "Typy zpráv", selectionGuide: "Příručka", api: "API", contact: "Kontakt", privacy: "Ochrana soukromí", terms: "Podmínky", editorial: "Redakční zásady", structuredAddress: "Termín strukturované adresy", faq: "Časté dotazy", glossary: "Slovník pojmů", changelog: "Historie změn", langMenuLabel: "Změnit jazyk", skipToContentLabel: "Přejít na obsah", returnToTopLabel: "Zpět nahoru", outlineLabel: "Na této stránce", appearanceLabel: "Vzhled", lightModeSwitchTitle: "Přepnout na světlý motiv", darkModeSwitchTitle: "Přepnout na tmavý motiv", searchButtonText: "Hledat", searchButtonAriaLabel: "Hledat", lastUpdatedText: "Poslední aktualizace", footerMessage: "Open-source ISO 20022 nástroje pro finanční týmy a inženýry.", footerCopyright: "Copyright © Sebastien Rousseau 2026", footerNavLabel: "Navigace v zápatí", documentation: "Dokumentace", resources: "Zdroje", legal: "Právní", releases: "Vydání", opensInNewTab: "(otevře se v nové kartě)", mainNavigation: "Hlavní navigace", extraNavigation: "Další navigace", mobileNavigation: "Mobilní navigace", toggleDarkMode: "Přepnout tmavý režim", github: "GitHub", pypi: "PyPI", docs: "O pacs.008", pacsExplained: "Technické podrobnosti", copyright: "Copyright", navMessages: "Zprávy", navResources: "Zdroje" },
  ha: { home: "Gida", breadcrumb: "Hanyar kewayawa", about: "Menene pacs.008?", messageTypes: "Nau'o'in saƙo", selectionGuide: "Littafin jagora", api: "API", contact: "Tuntuɓi", privacy: "Sirri", terms: "Sharuɗɗa", editorial: "Manufar edita", structuredAddress: "Lokacin adireshin tsari", faq: "Tambayoyi", glossary: "Ƙamus", changelog: "Tarihin canji", langMenuLabel: "Canja harshe", skipToContentLabel: "Tsallake zuwa abun ciki", returnToTopLabel: "Koma sama", outlineLabel: "A wannan shafin", appearanceLabel: "Bayyanar", lightModeSwitchTitle: "Canja zuwa haske", darkModeSwitchTitle: "Canja zuwa duhu", searchButtonText: "Bincika", searchButtonAriaLabel: "Bincika", lastUpdatedText: "An ƙarshe sabunta", footerMessage: "Kayan aikin ISO 20022 na buɗe don ƙungiyoyin kuɗi da injiniyoyi.", footerCopyright: "Haƙƙin mallaka © Sebastien Rousseau 2026", footerNavLabel: "Kewayawan ƙasa", documentation: "Takaddun shaida", resources: "Albarkatu", legal: "Shari'a", releases: "Fitarwa", opensInNewTab: "(yana buɗewa a sabon shafi)", mainNavigation: "Babban kewayawa", extraNavigation: "Ƙarin kewayawa", mobileNavigation: "Kewayawan hannu", toggleDarkMode: "Canja yanayin duhu", github: "GitHub", pypi: "PyPI", docs: "Game da pacs.008", pacsExplained: "Cikakken bayani na fasaha", copyright: "Haƙƙin mallaka", navMessages: "Saƙonni", navResources: "Albarkatu" },
  sv: { home: "Hem", breadcrumb: "Brödsmulor", about: "Vad är pacs.008?", messageTypes: "Meddelandetyper", selectionGuide: "Handbok", api: "API", contact: "Kontakt", privacy: "Integritet", terms: "Villkor", editorial: "Redaktionell policy", structuredAddress: "Tidsfrist för strukturerad adress", faq: "Vanliga frågor", glossary: "Ordlista", changelog: "Ändringslogg", langMenuLabel: "Byt språk", skipToContentLabel: "Hoppa till innehåll", returnToTopLabel: "Tillbaka till toppen", outlineLabel: "På den här sidan", appearanceLabel: "Utseende", lightModeSwitchTitle: "Byt till ljust tema", darkModeSwitchTitle: "Byt till mörkt tema", searchButtonText: "Sök", searchButtonAriaLabel: "Sök", lastUpdatedText: "Senast uppdaterad", footerMessage: "ISO 20022-verktyg med öppen källkod för finansteam och ingenjörer.", footerCopyright: "Copyright © Sebastien Rousseau 2026", footerNavLabel: "Sidfotsnavigering", documentation: "Dokumentation", resources: "Resurser", legal: "Juridik", releases: "Utgåvor", opensInNewTab: "(öppnas i ny flik)", mainNavigation: "Huvudnavigering", extraNavigation: "Extra navigering", mobileNavigation: "Mobilnavigering", toggleDarkMode: "Växla mörkt läge", github: "GitHub", pypi: "PyPI", docs: "Om pacs.008", pacsExplained: "Tekniska detaljer", copyright: "Copyright", navMessages: "Meddelanden", navResources: "Resurser" },
  tl: { home: "Home", breadcrumb: "Breadcrumb", about: "Ano ang pacs.008?", messageTypes: "Mga uri ng mensahe", selectionGuide: "Handbook", api: "API", contact: "Makipag-ugnayan", privacy: "Privacy", terms: "Mga tuntunin", editorial: "Patakaran sa editorial", structuredAddress: "Deadline ng structured address", faq: "Mga tanong", glossary: "Talasalitaan", changelog: "Talaan ng pagbabago", langMenuLabel: "Palitan ang wika", skipToContentLabel: "Lumaktaw sa nilalaman", returnToTopLabel: "Bumalik sa itaas", outlineLabel: "Sa pahinang ito", appearanceLabel: "Hitsura", lightModeSwitchTitle: "Lumipat sa maliwanag na tema", darkModeSwitchTitle: "Lumipat sa madilim na tema", searchButtonText: "Maghanap", searchButtonAriaLabel: "Maghanap", lastUpdatedText: "Huling na-update", footerMessage: "Open-source ISO 20022 na mga tool para sa mga koponan sa pananalapi at mga inhinyero.", footerCopyright: "Copyright © Sebastien Rousseau 2026", footerNavLabel: "Footer na navigasyon", documentation: "Dokumentasyon", resources: "Mga mapagkukunan", legal: "Legal", releases: "Mga release", opensInNewTab: "(magbubukas sa bagong tab)", mainNavigation: "Pangunahing navigasyon", extraNavigation: "Karagdagang navigasyon", mobileNavigation: "Mobile na navigasyon", toggleDarkMode: "I-toggle ang dark mode", github: "GitHub", pypi: "PyPI", docs: "Tungkol sa pacs.008", pacsExplained: "Mga teknikal na detalye", copyright: "Copyright", navMessages: "Mga mensahe", navResources: "Mga mapagkukunan" },
  yo: { home: "Ilé", breadcrumb: "Ọ̀nà àbáwọlé", about: "Kí ni pacs.008?", messageTypes: "Irú ìfiránṣẹ́", selectionGuide: "Ìwé àfọwọ́kọ", api: "API", contact: "Kàn sí wa", privacy: "Àṣírí", terms: "Àwọn ìlànà", editorial: "Ìlànà àtúnṣe", structuredAddress: "Àkókò àdírẹ́sì ọ̀nà", faq: "Àwọn ìbéèrè", glossary: "Àtòjọ ọ̀rọ̀", changelog: "Àkọsílẹ̀ àyípadà", langMenuLabel: "Yí èdè padà", skipToContentLabel: "Fò lọ sí àkóónú", returnToTopLabel: "Padà sí òkè", outlineLabel: "Lórí ojú-ìwé yìí", appearanceLabel: "Ìrísí", lightModeSwitchTitle: "Yí padà sí ìmọ́lẹ̀", darkModeSwitchTitle: "Yí padà sí òkùnkùn", searchButtonText: "Wá", searchButtonAriaLabel: "Wá", lastUpdatedText: "Ìgbà tí a ṣe àtúnṣe kẹ́hìn", footerMessage: "Irinṣẹ́ ISO 20022 orísun-ṣíṣí fún àwọn ẹgbẹ́ ìṣúná àti àwọn onímọ̀ ẹ̀rọ.", footerCopyright: "Ẹ̀tọ́ dáadáa © Sebastien Rousseau 2026", footerNavLabel: "Ìlílọ́ ẹsẹ̀-ìwé", documentation: "Àkọsílẹ̀", resources: "Àwọn ohun àmúlò", legal: "Òfin", releases: "Àwọn ẹ̀dà", opensInNewTab: "(ṣí sí ojú-ìwé tuntun)", mainNavigation: "Ìlílọ́ àkọ́kọ́", extraNavigation: "Ìlílọ́ àfikún", mobileNavigation: "Ìlílọ́ alágbèéká", toggleDarkMode: "Yí ọ̀nà dúdú padà", github: "GitHub", pypi: "PyPI", docs: "Nípa pacs.008", pacsExplained: "Àwọn àlàyé ìmọ̀-ẹ̀rọ", copyright: "Ẹ̀tọ́ dáadáa", navMessages: "Àwọn ìfiránṣẹ́", navResources: "Àwọn ohun àmúlò" }
};

export function getUiStrings(locale: string): UiStrings {
  const key = (LOCALES.includes(locale as LocaleKey) ? locale : "en") as LocaleKey;
  return { ...en, ...UI_STRINGS[key] };
}
