/**
 * Shared helpers for tests that assert against the deployed ssg output.
 *
 * The site is built by the Rust `ssg` CLI (see build.sh) into `public/`.
 * Tests MUST read from `public/` — the actual deployed tree — so that a
 * green test run is evidence about what ships, not about a build artefact
 * that no longer exists.
 */
import { readFileSync, existsSync, readdirSync } from "fs";
import { resolve } from "path";

/** The deployed output directory produced by `./build.sh`. */
export const DIST = resolve(__dirname, "../public");

/** Locales generated by scripts/generate-locales.mjs, excluding the "en" root. */
export const LOCALES = [
  "ar", "bn", "cs", "de", "es", "fr", "ha", "he", "hi", "id", "it", "ja",
  "ko", "nl", "pl", "pt", "ro", "ru", "sv", "th", "tl", "tr", "uk", "vi",
  "yo", "zh", "zh-tw",
];

/**
 * Read a built page. Pass "." for the homepage, otherwise a route such as
 * "about" or "fr/about".
 */
export function readPage(route: string): string {
  const file =
    route === "." ? resolve(DIST, "index.html") : resolve(DIST, route, "index.html");
  return readFileSync(file, "utf-8");
}

/** True when a built route has an index.html. */
export function pageExists(route: string): boolean {
  const file =
    route === "." ? resolve(DIST, "index.html") : resolve(DIST, route, "index.html");
  return existsSync(file);
}

/**
 * All CSS shipped by the build, concatenated.
 *
 * ssg emits content-hashed stylesheets into `public/_csp/`, so filenames are
 * not stable across builds and must never be hardcoded in assertions.
 */
export function allCss(): string {
  const dir = resolve(DIST, "_csp");
  return readdirSync(dir)
    .filter((f) => f.endsWith(".css"))
    .map((f) => readFileSync(resolve(dir, f), "utf-8"))
    .join("\n");
}

/** Read a client-side script from the static/ source tree. */
export function readStaticJs(name: string): string {
  return readFileSync(resolve(__dirname, "../static/js", name), "utf-8");
}

/**
 * Visible text with tags stripped and whitespace collapsed.
 *
 * Needed because ssg wraps code samples in syntax-highlighting spans, so a
 * command like `pip install pacs008` never appears as one literal in the HTML.
 */
export function textOf(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, "")
    // Decode entities. ssg escapes apostrophes as &#x27;, so a French string
    // like "L'exigence" will not match its source text unless decoded — an
    // assertion comparing against translation data would fail on punctuation
    // rather than on content.
    .replace(/&#x27;|&apos;/gi, "'")
    .replace(/&quot;/gi, '"')
    .replace(/&#x2F;/gi, "/")
    .replace(/&nbsp;/gi, " ")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&amp;/gi, "&")
    .replace(/\s+/g, " ");
}

/**
 * ssg minifies HTML and drops quotes around simple attribute values, so
 * `href="/fr/"` ships as `href=/fr/`. This matches an attribute whose value
 * may be quoted or bare.
 */
export function attr(name: string, value: string): RegExp {
  const v = value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`${name}=(?:"${v}"|'${v}'|${v})(?=[\\s>])`);
}
